# Generated by Django 5.2.6 on 2025-09-27 15:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0004_alter_category_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], max_length=20)),
                ('value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('active', models.BooleanField(default=True)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('categories', models.ManyToManyField(blank=True, related_name='discounts', to='products.category')),
                ('products', models.ManyToManyField(blank=True, related_name='discounts', to='products.product')),
                ('users', models.ManyToManyField(blank=True, related_name='discounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
